# Generated by Django 5.2.17 on 2026-10-04 17:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('color', models.CharField(default='#e11d48', max_length=20)),
                ('brand_bg', models.CharField(default='bg-rose-600', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('avatar', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('role', models.CharField(default='Community Reviewer', max_length=80)),
                ('is_certified_critic', models.BooleanField(default=False)),
                ('critic_outlet', models.CharField(blank=True, max_length=160)),
                ('verification_status', models.CharField(default='none', max_length=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('preferred_platforms', models.ManyToManyField(blank=True, related_name='preferred_by', to='api.platform')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.SlugField(max_length=180, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('release_year', models.PositiveSmallIntegerField()),
                ('seasons', models.PositiveSmallIntegerField(default=1)),
                ('episodes', models.PositiveSmallIntegerField(default=1)),
                ('poster_url', models.URLField(blank=True)),
                ('backdrop_url', models.URLField(blank=True)),
                ('age_rating', models.CharField(blank=True, max_length=12)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Ended', 'Ended'), ('Upcoming', 'Upcoming')], default='Ongoing', max_length=12)),
                ('creator', models.CharField(blank=True, max_length=180)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_top_rated', models.BooleanField(default=False)),
                ('is_recently_added', models.BooleanField(default=False)),
                ('radar_metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='series', to='api.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='api.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=8)),
                ('contains_spoilers', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.series')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('rated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='api.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_ratings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('watching', 'Watching'), ('plan_to_watch', 'Plan to watch'), ('completed', 'Completed')], default='plan_to_watch', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='api.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=4)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='api.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'user'), name='unique_review_vote')],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 10)), name='review_rating_1_to_10'),
        ),
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.UniqueConstraint(fields=('user', 'series'), name='unique_user_series_rating'),
        ),
        migrations.AddConstraint(
            model_name='userrating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 10)), name='user_rating_1_to_10'),
        ),
        migrations.AddConstraint(
            model_name='watchlistitem',
            constraint=models.UniqueConstraint(fields=('user', 'series'), name='unique_user_watchlist_series'),
        ),
    ]
